### PR TITLE
Replace usage of Pose2D with LegacyPose2D

### PR DESCRIPTION
**Pull request by vdiluoffo**
Please see issue #5

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the pr, someone will look into it asap.

**Comment by rohbotics** [comment]
Thanks @vdiluoffo.

The changes looks good they and fix the complication errors, but I don't have a turtlebot to test them out on.

Can anyone test the changes on a physical robot?

**Comment by wjwwood** [comment]
I think the fix is simple enough that if it compiles (I didn't test that myself), then it is probably good to merge. Unless you think there is a conceptual difference in the two types that may cause an issue.

**Comment by rohbotics** [comment]
I am not sure if the way that `kobuki_driver` handles things internally is the same with the new types,
especially because the changes were needed because of what seems like a refactor in `kobuki_driver`/ecl.

Discourse thread here: https://discourse.ros.org/t/turtlebot2-demo-with-beta-1-build-issue/1051/4

@stonier Can you confirm that this change is all that is needed to get this to work?

**Comment by stonier** [comment]
If they are the only instances of that class, yes, that is all that is needed. You can see the reference commit over in the ros 1 kobuki_node package [here](https://github.com/yujinrobot/kobuki/commit/27dc62752d9ec9bd3b110dee807ef8bfeda7709d). I do not think there was any other significant change in kobuki code going from indigo to kinetic.

**Comment by rohbotics** [comment]
Ok, as it is just a type name change I think it is good to merge.
@wjwwood do you agree?

Also can the commit comment be changed when we do the merge?

**Comment by wjwwood** [comment]
Sounds good to me, I can rewrite the commit message on merge.

**Comment by wjwwood** [comment]
Thanks @vdiluoffo.

**Pull request merged**
