### PR TITLE
fix isolated build by adding missing dep

### PR DESCRIPTION
**Pull request by gerkey**

### CODE REVIEW

**Comment by gerkey** [comment]
http://ci.ros2.org/job/ci_turtlebot-demo/20

**Review by mikaelarguedas — APPROVED** [review]
LGTM with passing CI,
note: dumb_teleop below likely doesn't need to link against nav_msgs either

**Comment by gerkey** [comment]
Removed `nav_msgs` from build of `dump_teleop` in 099d04d.

**Comment by gerkey** [comment]
That package now builds:

http://ci.ros2.org/job/ci_turtlebot-demo/20/console#console-section-152

I'll wait for test results before merging.

**Comment by gerkey** [comment]
Tests are clean, with one warning in another package, which I'll fix separately.

**Pull request merged**
