### PR TITLE
update README

### PR DESCRIPTION
**Pull request by mikaelarguedas**
These instructions rely on the trimmed turtlebot2_demo repos file from https://github.com/ros2/turtlebot2_demo/pull/20

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
https://github.com/ros2/turtlebot2_demo/pull/20 has merged.

**Comment by mikaelarguedas** [comment]
ready for review

**Review by dirk-thomas — APPROVED** [review]
LGTM but I haven't tried any of it.

**Comment by mikaelarguedas** [comment]
I updated it based on my testing so I'm going to merge it as is. If I get a chance to retry everything on a blank SD card and notice fixes that need to be made I'll open a follow-up

**Pull request merged**
