### PR TITLE
add missing maintainer names

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@ros2/team should we keep Brian as the maintainer of these 2 packages?

### CODE REVIEW

**Comment by clalancette** [comment]
> @ros2/team should we keep Brian as the maintainer of these 2 packages?

We should probably make it one of us.  Brian is not going to have time to look at buildfarm problems if they start failing, for instance.  I'm happy to take these if everyone wants me to.

**Review by wjwwood — APPROVED** [review]
lgtm, I don't think it matters too much if we leave Brian on them for now, we can ask him about it when he gets back?

**Comment by wjwwood** [comment]
> We should probably make it one of us. Brian is not going to have time to look at buildfarm problems if they start failing, for instance.

👍 for that too.

**Comment by mikaelarguedas** [comment]
ok I added a description and put myself as a maintainer instead of @gerkey

**Comment by mikaelarguedas** [comment]
I'll level the version numbers in a follow-up commit. merging this as is

**Pull request merged**
