### PR TITLE
remove ceres solver to use the upstream version

### PR DESCRIPTION
**Pull request by mikaelarguedas**
connects to ros2/cartographer#3

### CODE REVIEW

**Comment by clalancette** [comment]
I'm not sure that this is going to work.  At least, on my Pine64 board, I don't see libceres available at all.  It does exist for amd64 and i386, but not for aarch64, it seems :(.

**Comment by nuclearsandwich** [comment]
Is it worth determining why upstream doesn't provide the package for aarch64? I think for simplicity's sake it's not worth switching to upstream for beta 3 unless both supported binarydeb platforms (amd64 and arm64) can stay consistent.

**Comment by mikaelarguedas** [comment]
After some investigation, the package available on Xenial  amd64 is broken as well. Things start to get better with ceres1.12 but so far only debian stretch has a properly packaged version available for all architecture (see https://discourse.ros.org/t/ceres-package/872/18 for more details)

**Comment by mikaelarguedas** [comment]
Closing this: ceres-solver packaging issue tracked [here](https://discourse.ros.org/t/ceres-package/872/18)

**Review by clalancette — APPROVED** [review]

**Pull request merged**
